-- these tables need to be created
CREATE TABLE ISSUES (ID INTEGER NOT NULL IDENTITY, TITLE VARCHAR(50) NOT NULL, DESCRIPTION VARCHAR(255), CREATIONDATE DATE, DEVELOPERID INTEGER, TYPE TINYINT NOT NULL, STATUS TINYINT NOT NULL, PRIORITY TINYINT, POINT TINYINT, ASSIGNEDWEEK TINYINT,  PRIMARY KEY (ID))

-- ass developers
INSERT INTO DEVELOPERS (name) VALUES('Sanjay Mishra');
INSERT INTO DEVELOPERS (name) VALUES('E Group Dev 1');
INSERT INTO DEVELOPERS (name) VALUES('E Group Dev 2');
INSERT INTO DEVELOPERS (name) VALUES('E Group Dev 3');

--add bugs
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (1, 'E group Test Proj. Bug 1', 'E group Test Proj. Bug 1 description', '2022-05-11 00:00:00', 2, 1, 3, 1, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (2, 'E group Test Proj. Bug 2', 'E group Test Proj. Bug 2 description', '2022-05-11 00:00:00', 1, 1, 2, 3, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (3, 'E group Test Proj. Bug 3', 'E group Test Proj. Bug 3 description', '2022-05-11 00:00:00', 2, 1, 1, 2, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (4, 'E group Test Proj. Bug 4', 'E group Test Proj. Bug 4 description', '2022-05-11 00:00:00', 1, 1, 2, 1, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (5, 'E group Test Proj. Bug 5', 'E group Test Proj. Bug 5 description', '2022-05-11 00:00:00', 1, 1, 3, 3, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (6, 'E group Test Proj. Bug 6', 'E group Test Proj. Bug 6 description', '2022-05-11 00:00:00', 1, 1, 1, 3, null);

-- add stories
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT, ASSIGNEDWEEK) VALUES (6, 'E group story 1', 'E group story 1 description', '2022-05-11 00:00:00', 1, 2, 3, null, 1, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT, ASSIGNEDWEEK) VALUES (7, 'E group story 2', 'E group story 2 description', '2022-05-11 00:00:00', 2, 2, 2, null, 2, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT, ASSIGNEDWEEK) VALUES (8, 'E group story 3', 'E group story 3 description', '2022-05-11 00:00:00', 3, 2, 2, null, 3, null);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (9, 'E group story 4', 'E group story 4 description', '2022-05-11 00:00:00', 1, 2, 2, null, 5);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (10, 'E group story 5', 'E group story 5 description', '2022-05-11 00:00:00', 4, 2, 2, null, 8);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (11, 'E group story 6', 'E group story 6 description', '2022-05-11 00:00:00', 2, 2, 2, null, 8);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (12, 'E group story 7', 'E group story 7 description', '2022-05-11 00:00:00', 3, 2, 2, null, 2);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (13, 'E group story 8', 'E group story 8 description', '2022-05-11 00:00:00', 4, 2, 2, null, 3);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (14, 'E group story 9', 'E group story 9 description', '2022-05-11 00:00:00', 2, 2, 2, null, 5);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (15, 'E group story 10', 'E group story 10 description', '2022-05-11 00:00:00', 2, 2, 2, null, 8);


INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (16, 'E group story 11', 'E group story 11 description', '2022-05-11 00:00:00', null, 2, 2, null, 1);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (17, 'E group story 12', 'E group story 12 description', '2022-05-11 00:00:00', null, 2, 2, null, 2);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (18, 'E group story 13', 'E group story 13 description', '2022-05-11 00:00:00', null, 2, 2, null, 3);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (19, 'E group story 14', 'E group story 14 description', '2022-05-11 00:00:00', null, 2, 2, null, 8);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (20, 'E group story 15', 'E group story 15 description', '2022-05-11 00:00:00', null, 2, 2, null, 8);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (21, 'E group story 16', 'E group story 16 description', '2022-05-11 00:00:00', null, 2, 2, null, 1);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (22, 'E group story 17', 'E group story 17 description', '2022-05-11 00:00:00', null, 2, 2, null, 2);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (23, 'E group story 18', 'E group story 18 description', '2022-05-11 00:00:00', null, 2, 2, null, 2);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (24, 'E group story 19', 'E group story 19 description', '2022-05-11 00:00:00', null, 2, 2, null, 5);
INSERT INTO ISSUES (ID, TITLE, DESCRIPTION, CREATIONDATE, DEVELOPERID, TYPE, STATUS, PRIORITY, POINT) VALUES (25, 'E group story 20', 'E group story 20 description', '2022-05-11 00:00:00', null, 2, 2, null, 8);


